name: "advance"
on:
  push:
  schedule:
    - cron: '*/10 * * * *'

concurrency: advance
jobs:
  "advance":
    runs-on: ubuntu-latest
    concurrency: advance-${{matrix.jobs.branch}}-${{matrix.jobs.target}}
    steps:
    - { "uses": "actions/checkout@v2", "with": { "ref": "main" } }
    - name: prep
      uses: ./.github/actions/prep
      with:
        sopsAgeKey: "${{ secrets.SOPS_AGE_KEY }}"
    - name: "advance"
      run: .github/exec .github/workflows/advance.sh
