image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      cachix use colemickens
      cachix use nixpkgs-wayland
    command: |
      direnv allow
vscode:
  extensions:
    - bbenoist.Nix
    - rogalmic.bash-debug
    - mads-hartmann.bash-ide-vscode
