substitutions:
  ipnum: "121"
  devname: gosundsw${ipnum}

# bathroom vanity light

esphome:
  name: ${devname}
  platform: ESP8266
  board: esp01_1m

### START COMMON (TODO extract, make sure interpolation happens after concat)

wifi:
  ssid: "chimera-iot"
  password: "fafc996b949b6d53800"

  manual_ip:
    static_ip: 192.168.69.${ipnum}
    gateway: 192.168.1.1
    subnet: 255.255.0.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESPHome Fallback ${devname}"
    password: "d3ZBU8Kih1RN"

captive_portal:

api:
  password: "fafc996b949b6d53800"

logger:

ota:

### END COMMON

# GOSUND SW1v2 NOTE: This was IDd, the LED wasn't re
# GOSUND SW1v2 NOTE: I'm iffy on if the LEDs are configured correctly.
# TODO: extract this, it's common between gosund light-switches

# SW1
# GPIO #	Component
# GPIO00  	Button1
# GPIO01  	Led1i
# GPIO14  	Relay1
# GPIO16  	LedLinki
# FLAG  	None

# SW1v2
# GPIO #	Component
# GPIO00  	Button1
# GPIO02  	Led1i
# GPIO14  	Relay1
# GPIO16  	Led2i
# FLAG  	None

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
    id: ${devname}_button
    on_press:
      - switch.toggle: ${devname}_relay

switch:
  - platform: gpio
    id: ${devname}_relay_led
    name: "${devname} Relay LED"
    pin:
      number: GPIO02
      inverted: true
  - platform: gpio
    id: ${devname}_status_led
    name: ${devname}_status_led
    pin:
      number: GPIO16
      inverted: false
  - platform: gpio
    id: ${devname}_relay
    name: ${devname}_relay
    pin: GPIO14
    on_turn_on:
      - switch.turn_off: ${devname}_relay_led
      - switch.turn_off: ${devname}_status_led
    on_turn_off:
      - switch.turn_on: ${devname}_relay_led
      - switch.turn_on: ${devname}_status_led

#status_led:
#  id: ${devname}_status_led
#  name: ${devname}_status_led
#  pin:
#    number: GPIO16
#    inverted: yes

### COMMON SENSORS  ###
sensor:
  - platform: wifi_signal
    id: ${devname}_wifi_signal
    name: ${devname}_wifi_signal
    update_interval: 60s

  - platform: uptime
    id: ${devname}_uptime_val
    name: ${devname}_uptime_val

text_sensor:
  - platform: version
    id: ${devname}_esphome_version
    name: ${devname}_esphome_version
### COMMON SENSORS  ###
