substitutions:
  ipnum: "190"
  devname: ir${ipnum}_whynter

# generic template

esphome:
  name: ${devname}

esp32:
  board: nodemcu-32s

### START COMMON (TODO extract, make sure interpolation happens after concat)

wifi:
  ssid: "chimera-iot"
  password: "fafc996b949b6d53800"

  manual_ip:
    static_ip: 192.168.69.${ipnum}
    gateway: 192.168.1.1
    subnet: 255.255.0.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESPHomeFallback ${devname}"
    password: "d3ZBU8Kih1RN"

captive_portal:

api:
  password: "fafc996b949b6d53800"

logger:

ota:
### END COMMON

remote_transmitter:
  pin: GPIO16
  carrier_duty_percent: 50%

# TODO: replace this when it's upstreamed?
# https://github.com/esphome/feature-requests/issues/1767#issuecomment-1186649385
external_components:
  - source:
      type: git
      url: https://github.com/aeonsablaze/esphome
      ref: whynter-ac-support
    components: [ whynter ]

climate:
  - platform: whynter
    name: "AC"
    # sensor: room_temp
    use_fahrenheit: true
    supports_heat: false

# button:
#   - platform: template
#     name: "AC Cool Medium 21C"
#     on_press:
#       - remote_transmitter.transmit_raw:
#           code: 0xAA000AA7
