substitutions:
  ipnum: "101"
  devname:  mh_led${ipnum}

esphome:
  name: ${devname}
  platform: ESP8266
  board: esp8285


### START COMMON (TODO extract, make sure interpolation happens after concat)

wifi:
  ssid: "chimera-iot"
  password: "fafc996b949b6d53800"

  manual_ip:
    static_ip: 192.168.69.${ipnum}
    gateway: 192.168.1.1
    subnet: 255.255.0.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESPHome Fallback ${devname}"
    password: "d3ZBU8Kih1RN"

captive_portal:

api:
  password: "fafc996b949b6d53800"

logger:

ota:

### END COMMON


light:
  - platform: rgb
    name: "${devname}"
    red: mh_led_1
    green: mh_led_2
    blue: mh_led_3
    effects:
      - random:
          name: Random Effect With Custom Values
          transition_length: 8s
          update_interval: 11s

output:
  - platform: esp8266_pwm
    id: mh_led_1
    pin: GPIO5
  - platform: esp8266_pwm
    id: mh_led_2
    pin: GPIO12
  - platform: esp8266_pwm
    id: mh_led_3
    pin: GPIO13

