#cloud-config
runcmd:
  - |
    curl https://raw.githubusercontent.com/elitak/nixos-infect/master/nixos-infect \
      | PROVIDER=oracle \
        NIX_CHANNEL=nixos-21.05 \
          bash 2>&1 | tee /tmp/infect.log

# status - close but fails when nixos-infect fails
# - nixos infect makes some bad assumptions about /boot etc

# write_files:
# - path: /etc/nixos/host.nix
#   permissions: '0644'
#   content: |
#     {pkgs, ...}:
#     {
#       environment.systemPackages = with pkgs; [ vim ];
#     }
# runcmd:
#   - |
#     curl https://raw.githubusercontent.com/elitak/nixos-infect/master/nixos-infect \
#       | PROVIDER=oracle NIXOS_IMPORT=./host.nix NIX_CHANNEL=nixos-21.05 bash 2>&1 | tee /tmp/infect.log
