substitutions:
  ipnum: "111"
  devname: rdrnfc${ipnum}

esphome:
  name: ${devname}
  platform: ESP32
  board: esp32doit-devkit-v1

### START COMMON (TODO extract, make sure interpolation happens after concat)

wifi:
  ssid: "chimera-iot"
  password: "fafc996b949b6d53800"

  manual_ip:
    static_ip: 192.168.69.${ipnum}
    gateway: 192.168.1.1
    subnet: 255.255.0.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESPHome Fallback ${devname}"
    password: "d3ZBU8Kih1RN"

captive_portal:

api:
  password: "fafc996b949b6d53800"

logger:

ota:

### END COMMON

i2c:
  sda: GPIO21
  scl: GPIO22

pn532_i2c:
  id: pn532_board
  update_interval: 1s
  on_tag:
    then:
    - homeassistant.tag_scanned: !lambda 'return x;'
