name: prep
description: prep
author: cole
inputs:
  tailscaleAuthkey:
    description: 'tailscale authkey'
    required: true
runs:
  using: composite
  steps:
    - { "name": "Tailscale", "uses": "tailscale/github-action@v1", "with": { "authkey": "${{ inputs.tailscaleAuthkey }}" } }
    - { "uses": "cachix/install-nix-action@v14", "with": {"install_url": "https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.4pre20210823_af94b54/install","extra_nix_config": "experimental-features = nix-command flakes ca-references\n" } }
    - name: enable sshd
      shell: bash
      run: |
        mkdir -p ~/.ssh
        >>~/.ssh/authorized_keys echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC9YAN+P0umXeSP/Cgd5ZvoD5gpmkdcrOjmHdonvBbptbMUbI/Zm0WahBDK0jO5vfJ/C6A1ci4quMGCRh98LRoFKFRoWdwlGFcFYcLkuG/AbE8ObNLHUxAwqrdNfIV6z0+zYi3XwVjxrEqyJ/auZRZ4JDDBha2y6Wpru8v9yg41ogeKDPgHwKOf/CKX77gCVnvkXiG5ltcEZAamEitSS8Mv8Rg/JfsUUwULb6yYGh+H6RECKriUAl9M+V11SOfv8MAdkXlYRrcqqwuDAheKxNGHEoGLBk+Fm+orRChckW1QcP89x6ioxpjN9VbJV0JARF+GgHObvvV+dGHZZL1N3jr8WtpHeJWxHPdBgTupDIA5HeL0OCoxgSyyfJncMl8odCyUqE+lqXVz+oURGeRxnIbgJ07dNnX6rFWRgQKrmdV4lt1i1F5Uux9IooYs/42sKKMUQZuBLTN4UzipPQM/DyDO01F0pdcaPEcIO+tp2U6gVytjHhZqEeqAMaUbq7a6ucAuYzczGZvkApc85nIo9jjW+4cfKZqV8BQfJM1YnflhAAplIq6b4Tzayvw1DLXd2c5rae+GlVCsVgpmOFyT6bftSon/HfxwBE4wKFYF7fo7/j6UbAeXwLafDhX+S5zSNR6so1epYlwcMLshXqyJePJNhtsRhpGLd9M3UqyGDAFoOQ== cardno:7126708"
    - name: shell-out
      id: shell-out
      shell: bash
      run: echo "::set-output name=outpath::$(nix eval --raw '.#devShellSrc')"
    - name: shell-cache
      id: shell-cache
      uses: actions/cache@v2
      with:
        path: ./.nixcache/${{ steps.shell-out.outputs.outpath }}
        key: ${{ steps.shell-out.outputs.outpath }}
    - name: load-shell
      shell: bash
      run: |
        if [[ -d "./.nixcache/${{ steps.shell-out.outputs.outpath }}" ]]; then
          nix copy --no-check-sigs --from ./.nixcache/${{ steps.shell-out.outputs.outpath }} "${{ steps.shell-out.outputs.outpath }}"
          touch ./.nixcache/${{ steps.shell-out.outputs.outpath }}-loaded
        fi
    - name: "init"
      shell: bash
      run: .github/exec __init
    - name: save-shell
      shell: bash
      run: |
        set -x
        set +e
        if [[ ! -f ./.nixcache/${{ steps.shell-out.outputs.outpath }}-loaded ]]; then
          time nix build -L "${{ steps.shell-out.outputs.outpath }}"
          nix copy --no-check-sigs --to ./.nixcache/${{ steps.shell-out.outputs.outpath }} "${{ steps.shell-out.outputs.outpath }}"
        fi
        sleep 3600
