name: prep
description: prep
author: cole
# inputs:
  # skipInit:
  #   description: 'skip init (only useful for pre-caching the shell)'
  #   required: false
  #   default: 'false'
runs:
  using: composite
  steps:
    - { "name": "Tailscale", "uses": "tailscale/github-action@v1", "with": { "authkey": "${{ secrets.TAILSCALE_AUTHKEY }}" } }
    - { "uses": "cachix/install-nix-action@v14", "with": {"install_url": "https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.4pre20210823_af94b54/install","extra_nix_config": "experimental-features = nix-command flakes ca-references\n" } }
    - name: shell-out
      shell: bash
      run: |
        set -x
        echo "hello"
        outpath="$(nix eval --raw '.#devShellSrc')"
        echo "::set-output name=outpath::$outpath"
        echo "world"
    - name: shell-cache
      id: shell-cache
      uses: actions/cache@v2
      with:
        path: ./.nixcache/${{ steps.shell-out.outputs.outpath }}
        key: ${{ steps.shell-out.outputs.outpath }}
    - name: load-shell
      shell: bash
      run: |
        if [[ -d ./.nixcache ]]; then 
          nix copy --no-check-sigs --from ./.nixcache/${{ steps.shell-out.outputs.outpath }} "${{ steps.shell-out.outputs.outpath }}"
          touch ./.nixcache/${{ steps.shell-out.outputs.outpath }}-loaded
        fi
    - name: "init"
      shell: bash
      run: .github/exec __init
    - name: save-shell
      shell: bash
      run:
        if [[ ! -f ./.nixcache/${{ steps.shell-out.outputs.outpath }}-loaded ]]; then
          nix copy --no-check-sigs --to ./.nixcache/${{ steps.shell-out.outputs.outpath }} "${{ steps.shell-out.outputs.outpath }}"
        fi
