name: "Build"
on:
  push:
  schedule:
    - cron: '*/10 * * * *'
jobs:
  build:
    continue-on-error: true
    runs-on:
    - ${{matrix.jobs.runson}}
    concurrency: ${{matrix.jobs.branch}}-${{matrix.jobs.target}}
    strategy:
      matrix:
        jobs:
        - { "branch": "main",         "target": "toplevels.jeffhyper",  "runson": "ubuntu-latest" }
        - { "branch": "main",         "target": "toplevels.porty",      "runson": "ubuntu-latest" }
        - { "branch": "main",         "target": "toplevels.raisin",     "runson": "ubuntu-latest" }
        - { "branch": "main",         "target": "toplevels.rpizero1",   "runson": "ubuntu-latest" }
        - { "branch": "main",         "target": "toplevels.xeep",       "runson": "ubuntu-latest" }
        - { "branch": "auto-update",  "target": "toplevels.jeffhyper",  "runson": "ubuntu-latest" }
        - { "branch": "auto-update",  "target": "toplevels.porty",      "runson": "ubuntu-latest" }
        - { "branch": "auto-update",  "target": "toplevels.raisin",     "runson": "ubuntu-latest" }
        - { "branch": "auto-update",  "target": "toplevels.rpizero1",   "runson": "ubuntu-latest" }
        - { "branch": "auto-update",  "target": "toplevels.xeep",       "runson": "ubuntu-latest" }
        #- { "branch": "main",         "target": "bundles.x86_64-linux", "runson": "self-hosted" }
        #- { "branch": "auto-update",  "target": "bundles.x86_64-linux", "runson": "self-hosted" }
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # flakes doesn't work on shallow clones
        ref: ${{ matrix.jobs.branch }}
    - uses: cachix/install-nix-action@v12
      # with:
      #   install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210429_d15a196/install
      #   extra_nix_config: |
      #     experimental-features = nix-command flakes ca-references
    - uses: cachix/cachix-action@v10
      if: ${{ matrix.jobs.runson != 'self-hosted' }}
      with:
        name: colemickens
        signingKey: '${{ secrets.cachix_key_colemickens }}'
    - name: git-setup
      env:
        CACHIX_SIGNING_KEY: "${{ secrets.cachix_key_colemickens }}"
      run: |
        git config --global user.name 'Cole Botkens'
        git config --global user.email 'cole.mickens+colebot@gmail.com'
        nix-shell --run "cachix watch-store colemickens &"
    - name: build-and-cache
      env:
        CACHIX_SIGNING_KEY: "${{ secrets.cachix_key_colemickens }}"
      run: |
        set -xeuo pipefail
        # nix develop -c ./nixup nbuc "${{ matrix.jobs.target }}"
        nix-shell --run "./nixup nbuc ${{ matrix.jobs.target }}"

