name: "Build"
on:
  push:
#  schedule:
#    - cron: '*/10 * * * *'
jobs:
  build:
    runs-on:
    - ubuntu-latest
#    - ${{matrix.jobs.os}}
    strategy:
      matrix:
        jobs:
        #- { "os": "arm64", "arch": "aarch64-linux", "target": "toplevels.rpifour1" }
        #- { "os": "arm64", "arch": "aarch64-linux", "target": "toplevels.pinebook" }
        - { "os": "x86",   "arch": "x86_64-linux" , "target": "toplevels.xeep" }
        - { "os": "x86",   "arch": "x86_64-linux" , "target": "toplevels.azdev" }
        - { "os": "x86",   "arch": "x86_64-linux" , "target": "toplevels.porty" }
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # flakes doesn't work on shallow clones
    - uses: cachix/install-nix-action@v12
      #with:
        #install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210429_d15a196/install
        #extra_nix_config: |
        #  experimental-features = nix-command flakes ca-references
    - name: git-setup
      run: |
        git config --global user.name 'Cole Botkens'
        git config --global user.email 'cole.mickens+colebot@gmail.com'
    - name: build
      run: |
        set -xeuo pipefail

        # flakes
        # nix develop -c ./nixup nbf "${{ matrix.jobs.target }}"

        # stable
        np="https://github.com/$(jq -r '.nodes.nixpkgs.locked.owner' flake.lock)/$(jq -r '.nodes.nixpkgs.locked.repo' flake.lock)/archive/$(jq -r '.nodes.nixpkgs.locked.rev' flake.lock).tar.gz"
        nix-shell -I nixpkgs=${np} --run "./nixup nbl ${{matrix.jobs.target}}"
    - name: cache
      env:
        CACHIX_SIGNING_KEY: "${{ secrets.cachix_key_colemickens }}"
      run: |
        set -xeuo pipefail

        # flakes
        # readlink -f ./result | nix develop -c cachix push colemickens

        # stable
        np="https://github.com/$(jq -r '.nodes.cachix.locked.owner' flake.lock)/$(jq -r '.nodes.cachix.locked.repo' flake.lock)/archive/$(jq -r '.nodes.cachix.locked.rev' flake.lock).tar.gz"
        readlink -f ./result | nix-shell -I nixpkgs=${np} -p cachix --run 'cachix push colemickens'
