name: "Update"
on:
  push:
  schedule:
    - cron: '*/10 * * * *'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
          # Nix Flakes doesn't work on shallow clones
          fetch-depth: 0
    - uses: cachix/install-nix-action@v12
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20201221_9fab14a/install
        extra_nix_config: |
          experimental-features = nix-command flakes
    - name: git-setup
      run: |
        nix-shell -I 'nixpkgs=https://github.com/nixos/nixpkgs/archive/nixos-unstable.tar.gz' -p git --command "git config --global user.name 'Cole Botkens'"
        nix-shell -I 'nixpkgs=https://github.com/nixos/nixpkgs/archive/nixos-unstable.tar.gz' -p git --command "git config --global user.email 'cole.mickens+colebot@gmail.com'"
        git checkout -b auto-update
    - name: update-flake
      run: |
        nix-shell -I 'nixpkgs=https://github.com/nixos/nixpkgs/archive/nixos-unstable.tar.gz' \
          -p nixUnstable --command \
            "nix --experimental-features 'nix-command flakes' flake update --commit-lock-file --no-registries"
    - name: update
      run: |
        nix-shell --pure --command "JOB_ID=\"GHA-${GITHUB_WORKFLOW}-${GITHUB_RUN_ID}-${GITHUB_RUN_NUMBER}\" ./nixup update"
    - name: push
      run: |
        git push origin HEAD -f
