name: "Build"
on:
  push:
  schedule:
    - cron: '*/10 * * * *'
jobs:
  build:
    runs-on: [ ubuntu-latest ]
    strategy:
      matrix:
        jobs:
        - { "os": "arm64", "arch": "aarch64-linux", "target": "toplevels.rpifour1" }
        - { "os": "arm64", "arch": "aarch64-linux", "target": "toplevels.pinebook" }
        - { "os": "x86",   "arch": "x86_64-linux" , "target": "toplevels.xeep" }
        - { "os": "x86",   "arch": "x86_64-linux" , "target": "toplevels.azdev" }
    steps:
    - uses: actions/checkout@v2
      with:
          # Nix Flakes doesn't work on shallow clones
          fetch-depth: 0
    - uses: cachix/install-nix-action@v12
      with:
        install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20201221_9fab14a/install
        extra_nix_config: |
          experimental-features = nix-command flakes ca-derivations ca-references
    - name: build
      run: |
        nix-shell --pure --command "JOB_ID=\"GHA-${GITHUB_WORKFLOW}-${GITHUB_RUN_ID}-${GITHUB_RUN_NUMBER}\" ./nixup update"
