name: "Build"
on:
  push:
  schedule:
    - cron: '*/20 * * * *'
jobs:
  build:
    continue-on-error: true
    runs-on:
    - ${{matrix.jobs.runson}}
    concurrency: ${{matrix.jobs.branch}}-${{matrix.jobs.target}}
    strategy:
      matrix:
        jobs:
        - { "branch": "main",         "target": "toplevels.jeffhyper",  "runson": "ubuntu-latest" }
        - { "branch": "main",         "target": "toplevels.porty",      "runson": "ubuntu-latest" }
        - { "branch": "main",         "target": "toplevels.raisin",     "runson": "ubuntu-latest" }
        - { "branch": "main",         "target": "toplevels.rpizero1",   "runson": "ubuntu-latest" }
        - { "branch": "main",         "target": "toplevels.xeep",       "runson": "ubuntu-latest" }
        - { "branch": "auto-update",  "target": "toplevels.jeffhyper",  "runson": "ubuntu-latest" }
        - { "branch": "auto-update",  "target": "toplevels.porty",      "runson": "ubuntu-latest" }
        - { "branch": "auto-update",  "target": "toplevels.raisin",     "runson": "ubuntu-latest" }
        - { "branch": "auto-update",  "target": "toplevels.rpizero1",   "runson": "ubuntu-latest" }
        - { "branch": "auto-update",  "target": "toplevels.xeep",       "runson": "ubuntu-latest" }
        #- { "branch": "main",         "target": "bundles.x86_64-linux", "runson": "self-hosted" }
        #- { "branch": "auto-update",  "target": "bundles.x86_64-linux", "runson": "self-hosted" }
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ matrix.jobs.branch }}
    - uses: cachix/install-nix-action@v13
      with:
        #install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210429_d15a196/install
        install_url: "https://nixos-nix-install-tests.cachix.org/serve/dznj18ywp62vghk98m5vclfqmszjnbph/install"
        install_options: "--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve"
        extra_nix_config: |
          experimental-features = nix-command flakes ca-references
    - name: prepare
      run: .github/exec nix-build --version
    - name: git-setup
      run: |
        .github/exec git config --global user.name 'Cole Botkens'
        .github/exec git config --global user.email 'cole.mickens+colebot@gmail.com'
    - name: build
      run: |
        set -xeuo pipefail
        export CI_JOB_ID="${GITHUB_RUN_ID}_${GITHUB_RUN_NUMBER}"
        .github/exec ./nixup ci_nbu "${{ matrix.jobs.target }}"
    - name: cache
      env:
        CACHIX_SIGNING_KEY: "${{ secrets.cachix_key_colemickens }}"
      run: |
        set -xeuo pipefail
        export CI_JOB_ID="${GITHUB_RUN_ID}_${GITHUB_RUN_NUMBER}"
        .github/exec ./nixup ci_cache "${{ matrix.jobs.target }}"
