name: "nixcfg-next"
concurrency: "nixcfg-next"
on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:
  push:
    branches:
      - "main"
jobs:
  "update":
    runs-on: "slynux-default"
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: next
      run: |
        nix develop .#ci -c ./ci-next.nu
