name: "precache-shell"
on:
  push:

concurrency: precache-shell
jobs:
  "cache":
    runs-on: ubuntu-latest
    steps:
    - { "uses": "actions/checkout@v2", "with": { "ref": "main" } }
    - name: prep
      uses: ./.github/actions/prep
      with:
        tailscaleAuthkey: "${{ secrets.TAILSCALE_AUTHKEY }}"