name: "simple"
on:
  push:

concurrency: simple
jobs:
  "simple-update":
    runs-on: ubuntu-latest
    concurrency: simple-${{matrix.jobs.branch}}-${{matrix.jobs.target}}
    steps:
    - { "uses": "actions/checkout@v2", "with": { "ref": "main" } }
    - name: prep
      uses: ./.github/actions/prep
      with:
        sopsAgeKey: "${{ secrets.SOPS_AGE_KEY }}"
    - name: "update"
      run: |
        cat << EOF | .github/exec
          set -x
          git checkout -b auto-simple
          git reset --hard main
          ./nixup lockup
          git push origin HEAD -f
        EOF
    - name: "build"
      run : |
        cat << EOF | .github/exec
          set -x
          ./nixup ciup
        EOF
    - name: "set-ready"
      run : |
        cat << EOF | .github/exec
          set -x
          git checkout -b auto-simple-ready
          git reset --hard origin/auto-simple
          git rebase origin/main
          git push origin HEAD -f
        EOF
    - name: "update2"
      run: |
        cat << EOF | .github/exec
          set -x
          git checkout -b auto-simple
          git reset --hard main
          ./nixup pkgup
          git push origin HEAD -f
        EOF
    - name: "build2"
      run : |
        cat << EOF | .github/exec
          set -x
          ./nixup ciup
        EOF
    - name: "set-ready2"
      run : |
        cat << EOF | .github/exec
          set -x
          git checkout -b auto-simple-ready2
          git reset --hard origin/auto-simple
          git rebase origin/main
          git push origin HEAD -f
        EOF
