name: "Update"
on:
  push:
  schedule:
    - cron: '*/10 * * * *'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: install nix
      uses: cachix/install-nix-action@v13
      with:
        #install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210429_d15a196/install
        install_url: "https://nixos-nix-install-tests.cachix.org/serve/dznj18ywp62vghk98m5vclfqmszjnbph/install"
        install_options: "--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve"
        extra_nix_config: |
          experimental-features = nix-command flakes ca-references
    - name: setup git
      run: |
        git config --global user.name 'Cole Botkens'
        git config --global user.email 'cole.mickens+colebot@gmail.com'
    - name: force-update auto-update
      env:
        CACHIX_SIGNING_KEY: "${{ secrets.cachix_key_colemickens }}"
      run: |
        set -xeuo pipefail
        git checkout -b auto-update
        nix develop --ignore-environment \
          --keep CACHIX_SIGNING_KEY \
          --keep HOME \
          -c ./nixup update
        git push origin HEAD -f
    - name: try-update auto-update-ready
      run: |
        set -xeuo pipefail
        git checkout -b auto-update-ready
        set +e
        nix develop --ignore-environment \
          --keep CACHIX_SIGNING_KEY \
          --keep HOME \
          -c ./nixup nbu_check 'required' \
        && git push origin HEAD -f
