name: "Update"
on:
  push:
  schedule:
    - cron: '*/10 * * * *'
jobs:
  "update":
    runs-on: ubuntu-latest
    concurrency: update-${{matrix.jobs.branch}}-${{matrix.jobs.target}}
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v13
    - name: (setup) pre-cache shell
      run: |
        .github/exec nix-build --version
    - name: (setup) configure git
      run: |
        .github/exec git config --global user.name 'Cole Botkens'
        .github/exec git config --global user.email 'cole.mickens+colebot@gmail.com'
        .github/exec git remote update
    - name: "(auto-update-ready): try advance"
      # note we must do this first
      # if we update "auto-update" first,
      # then we ALWAYS have the new git rev to build (for some build output product, not sure which)
      run: |
        set -xeuo pipefail
        .github/exec git checkout -b auto-update-ready
        .github/exec git branch --list --all
        .github/exec git reset --hard origin/auto-update
        .github/exec ./nixup nbu_check 'req.bld' \
          && .github/exec git push origin HEAD -f \
            || true
    - name: "(auto-update): update"
      env:
        CACHIX_SIGNING_KEY: "${{ secrets.cachix_key_colemickens }}"
      run: |
        set -xeuo pipefail
        export CI_JOB_ID="${GITHUB_RUN_ID}_${GITHUB_RUN_NUMBER}"
        .github/exec git checkout -b auto-update
        .github/exec git reset --hard main
        .github/exec ./nixup update
        .github/exec ./nixup update-pkgs
        .github/exec git push origin HEAD -f
