name: "Update2"
on:
  push:

concurrency: update2
jobs:
  "update":
    runs-on: ubuntu-latest
    concurrency: update2-${{matrix.jobs.branch}}-${{matrix.jobs.target}}
    steps:
    - { "uses": "actions/checkout@v2", "with": { "ref": "main" } }
    - { "name": "Tailscale", "uses": "tailscale/github-action@v1", "with": { "authkey": "${{ secrets.TAILSCALE_AUTHKEY }}" } }
    - { "uses": "cachix/install-nix-action@v14", "with": {"install_url": "https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.4pre20210823_af94b54/install","extra_nix_config": "experimental-features = nix-command flakes ca-references\n" } }
    - name: "init"
      run: |
        set -x
        .github/exec __init
    - name: "packet-create-instances"
      env: { "NIXUP_SECRETS": "${{ secrets.NIXUP_SECRETS }}" }
      run: .github/exec ./nixup packet-up
    - name: "update"
      env: { "NIXUP_SECRETS": "${{ secrets.NIXUP_SECRETS }}" }
      run: |
        export CI_JOB_ID="${GITHUB_RUN_ID}_${GITHUB_RUN_NUMBER}"
        cat << EOF | .github/exec
          git checkout -b auto-update2
          git reset --hard main
          ./nixup update
          ./nixup update-pkgs
          git push origin HEAD -f
        EOF

  "build":
    needs: "update"
    runs-on:
    - ${{matrix.jobs.runson}}
    concurrency: build2-${{matrix.jobs.branch}}-${{matrix.jobs.target}}
    strategy:
      matrix:
        jobs:
        - { "branch": "auto-update2",  "target": "bundles.x86_64-linux",   "runson": "gha-x64" }
        - { "branch": "auto-update2",  "target": "bundles.aarch64-linux",  "runson": "gha-arm64" }
    steps:
    - { "uses": "actions/checkout@v2", "with": { "ref": "auto-update2" } }
    - { "name": "Tailscale", "uses": "tailscale/github-action@v1", "with": { "authkey": "${{ secrets.TAILSCALE_AUTHKEY }}" } }
    - { "uses": "cachix/install-nix-action@v14", "with": {"install_url": "https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.4pre20210823_af94b54/install","extra_nix_config": "experimental-features = nix-command flakes ca-references\n" } }
    - name: Tailscale
      uses: tailscale/github-action@v1
      with:
        authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
    - uses: cachix/install-nix-action@v14
    - name: "init"
      run: .github/exec __init
    - name: build-n-cache
      env: { "NIXUP_SECRETS": "${{ secrets.NIXUP_SECRETS }}" }
      run: .github/exec ./nixup ci_nb_cache ${{ matrix.jobs.target }}

  "publish":
    needs: "build"
    runs-on: ubuntu-latest
    steps:
    - { "uses": "actions/checkout@v2", "with": { "ref": "auto-update2" } }
    - { "name": "Tailscale", "uses": "tailscale/github-action@v1", "with": { "authkey": "${{ secrets.TAILSCALE_AUTHKEY }}" } }
    - { "uses": "cachix/install-nix-action@v14", "with": {"install_url": "https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.4pre20210823_af94b54/install","extra_nix_config": "experimental-features = nix-command flakes ca-references\n" } }
    - name: "init"
      run: .github/exec __init
    - name: "publish"
      env: { "NIXUP_SECRETS": "${{ secrets.NIXUP_SECRETS }}" }
      run: |
        cat << EOF | .github/exec
          set -x
          git log -n 5 --oneline origin/main
          git log -n 5 --oneline origin/auto-update2
          git checkout -b auto-update2-ready
          git reset --hard origin/auto-update2
          git rebase origin/main
        EOF
        cat << EOF | .github/exec
          ./nixup ci_check
          git push origin HEAD -f
        EOF || true

  # "cleanup":
  #   needs: "publish"
  #   if: ${{ always() }}
  #   runs-on: ubuntu-latest
    # steps:
    # - { "uses": "actions/checkout@v2", "with": { "ref": "auto-update2" } }
    # - { "name": "Tailscale", "uses": "tailscale/github-action@v1", "with": { "authkey": "${{ secrets.TAILSCALE_AUTHKEY }}" } }
    # - { "uses": "cachix/install-nix-action@v14", "with": {"install_url": "https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.4pre20210823_af94b54/install","extra_nix_config": "experimental-features = nix-command flakes ca-references\n" } }
  #     run: .github/exec __init
  #   - name: "packet-destroy-instances"
  #     if: ${{ always() }}
  #    env: { "NIXUP_SECRETS": "${{ secrets.NIXUP_SECRETS }}" }
  #     run: .github/exec ./nixup packet-down
