name: "Update"
on:
  push:
  schedule:
    - cron: '*/10 * * * *'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # flakes doesn't work on shallow clones
    - uses: cachix/install-nix-action@v12
      # with:
      #   install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210429_d15a196/install
      #   extra_nix_config: |
      #     experimental-features = nix-command flakes ca-references
    - name: git-setup
      run: |
        git config --global user.name 'Cole Botkens'
        git config --global user.email 'cole.mickens+colebot@gmail.com'
    - name: update
      run: |
        set -xeuo pipefail

        # flakes
        #nix develop -c ./nixup update

        # stable
        np="https://github.com/$(jq -r '.nodes.nixpkgs.locked.owner' flake.lock)/$(jq -r '.nodes.nixpkgs.locked.repo' flake.lock)/archive/$(jq -r '.nodes.nixpkgs.locked.rev' flake.lock).tar.gz"
        nix-shell -I nixpkgs=${np} --run "./nixup update"
    - name: push
      run: |
        git push origin HEAD -f
