# v4
creation_rules:
  - path_regex: .*$
    key_groups:
      - pgp: [  8A94ED58A476A13AE0D6E85E9758078DE5308308, ]
        age: [  age1y7xfw8pwv8z8mepasfkkfgnvln3s3hyv2s7vpwst6ce3a9qtg9cq34ztvr,  age1hzz5ldtts66d3eax9n726cpvelgc6vaun783e8nuaa072mw5x4nqpsrx90,  age15pfzj764rps90cp9y23plctcpgtsyndtcf05gd2xcj8r224tng5qmj3hyg,  age10hf77sthtrs05zevxakfeedzchsyl0tc5ydrxg9uj7fu0lq42gvs7yszf6,  age1dh0xcxkpaj4taq0hkn6ycqhcgc72f4m2j6ux02c07fsu3639nd2stxltes,  age1eaccgaj4tcksx6d23uud7hk8eszgml5pfky726qpksauejmsvddskzrhvq, ]
