# v4
creation_rules:
  - path_regex: .*$
    key_groups:
      - age: [  age1hzz5ldtts66d3eax9n726cpvelgc6vaun783e8nuaa072mw5x4nqpsrx90,  age15pfzj764rps90cp9y23plctcpgtsyndtcf05gd2xcj8r224tng5qmj3hyg,  age19e53yk3ny8ydn0untc79w62cq78ew3sq58r9uxfcgwqmy2jxup5q8hqm4g,  age1xcwhcua9equ4edtqtzag3nf3j3ws7avj9q8pptdkqsmpqasksflsgmjz5h,  age1zqw85uf6veqjwmeppa5x3vg3wtk4s3afzxsc7gu5n402q0tfg4tq59sw3m,  age1dh0xcxkpaj4taq0hkn6ycqhcgc72f4m2j6ux02c07fsu3639nd2stxltes,  age1uhtmnggzf6d4ew2g7wdl0am0plz9hfhqnr6ukfpzgc8r4xx49phqtcgws0, ]
