creation_rules:
  - path_regex: .*$
    key_groups:
      - pgp:
          - "4774EB1BF21D57E93221CF0262556A61E301DC21" # colemickens "bad" gpgkey (replace w/ solokey v2)
          - "EAE0488FD59B66251E9004D1D7FA118E53E6D398" # srht-builder manually made key
          - "5e654f4bb0e3b1114af9eccf4246a55397edb8e9" # ssh-to-pgp(xeep /etc/ssh/host_ed25519_key.pub)
          - "d5dea60b278a0e2fa042a2d8927cb3143b779663" # ssh-to-pgp(rpione /etc/ssh/host_ed25519_key.pub)
          - "4149F15AA92C896C3DECE707B482CC5C93B3C12C" # ssh-to-pgp(pinebook host-rsa)
          - "fda31681df62826f9359e1e621d4fdcd337617e6" # ssh-to-pgp(rpitwo host-rsa)
          - "ffa1a43874729edf86b1ed0f1e38b1dc3f0737a0" # ssh-to-pgp(raisin host-rsa)
          - "75b4c4b6713a99edac9debc7f6ded4a967bf21e6" # ssh-to-pgp(porty host-rsa)
          - "9800b3ce7c1c4ccfbd09095bd4ef0760fad2a89d" # ssh-to-pgp(jeffhyper host-rsa)
          - "b050543943855d3d3e1e11f21468a5b3982940bd" # ssh-to-pgp(pinephone host-rsa)
          - "e3dac187bd81bfb5eb5ce61698ff4bf515caed25" # ssh-to-pgp (sinkor host-rsa)
          - "4575f8b1df7dfa3958fd1c955adb45068448fd7e" # ssh-to-pgp (enchilada host-rsa)
        age:
          - "age1qeav4nazvqudr0p55dq8thqlftplu4pu279vt6wddjzvdjfrgsyqr5qt68" # (gha-age-key-pub)
